### ISSUE TITLE
Create server with local database storage

### ISSUE THREAD

**Issue by borud** [ExploratoryEngineering/air-quality-sensor-node#3]
Accept `Sample` messages from Horde and store them to a database.
- [x] Create initial protobuf schema
- [x] Create SQL schema
- [x] Create Horde listener
- [x] Create UDP listener
- [x] Create processing pipeline
- [x] Create simple websockets listener
- [x] Pull older samples from Horde and store them locally

**Comment by pkkummermo** [comment]
A lot of inspiration can be taken from https://github.com/ExploratoryEngineering/tkaq as it solves the exact same use case.

**Comment by borud** [comment]
@pkkummermo I intend to ste...borrow liberally :-)
